version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8989}:${PORT:-8989}"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped 